version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql123
      MYSQL_DATABASE: sms
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot_container
    ports:
      - "8093:8093"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mysql123
    restart: always

volumes:
  db_data:
